title: "{{page_title}}"
slug: "{{page_title.lower().replace(' ', '_')}}"
notebooks:
  - example
parameters:
  page_title: "{{settings.default_page_title}}"
context:
  data_common.management.settings:
    - settings
options:
  rerun: true
  hide_input: true
upload:
  gdrive:
    g_folder_id: blank
    g_drive_id: blank